import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./provider";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <NavBar />
            <main className="max-w-7xl px-6 mx-auto">{children}</main>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
